### ISSUE TITLE
Advanced Collision: Airships in Icecrown

### ISSUE THREAD

**Issue by ghost** [arcemu/arcemu#13]
The bug is obvious, it is basically the same with elevators in undercity etc. NPC's/creatures are not really moved/blocked by gameobjects. When you have for instance creatures attacking you in the undercity and following you on the platform of the elevator, they will stay on the ground, passing through the platform.

The additional difficulty for the two airships in Northrend is, that they are actually moving. I am not sure how you would have to deal with this, but they would need corresponding to the airship's movement, moving spawn- and waypoints and somehow react to parts of the airship (so basically the gameobject) passing through them. 
What happens is, that they will all at some point of time float in mid-air, doing some fantastic swimming moves.

It's an advanced problem, and Collision/Pathfinding in a 3D environment is certainly not the easiest thing to accomplish, 
but I just mentioned it for the sake of a complete ToDo list ;)

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#95
