### ISSUE TITLE
Explosive Sheep

### ISSUE THREAD

**Issue by ghost** [arcemu/arcemu#17]
Explosive Sheep creates a companion that doesn't explode, doesn't attack but simply follows you.
It even follows you when the duration is over with, same applies to other engineered constructs, like Target Dummy.
Not sure wether this is a bug or it is simply a not implemented feature.

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#94

**Comment by dfighter1985** [comment]
Now it works. Hopefully well enough for it to be enjoyable.
Here's a video about it:
https://www.youtube.com/watch?v=Ay3c67WPyNA
