### ISSUE TITLE
Talentpoints left are not correct

### ISSUE THREAD

**Issue by Magnifikator** [arcemu/arcemu#206]
How to reproduce:
1. Make any new char, set him to level 30 f.ex 
2. Check his talentpoints left: 21 points, that's correct.
3. Open in a 2nd wow client any char and summon the first char.
4. By rightclicking on his avatar icon view his properties
5. Check his talentpoints left: 61 points, that's wrong

It shows always the max. talentpoints, independent how much are really left or are already assigned

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#34

**Comment by dfighter1985** [comment]
Thanks for reporting the issue!
