### ISSUE TITLE
Items with bonding=4 not lootable in gameobjects

### ISSUE THREAD

**Issue by Magnifikator** [arcemu/arcemu#307]
An item with bonding=4 (questitem) is not lootable in gameobjects.

F.ex. 
http://old.wowhead.com/object=190702

There's a GO 190702 that have inside the quest item 39063. However you can't loot this item in the GO.

If you set bonding=0 for the item 39063 it is lootable but it isn't shown as a quest item anymore of course.

It tried the same with another quest item:
http://www.wowhead.com/item=182 (Garrick's Head)

Same behaviour.

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#21

**Comment by dfighter1985** [comment]
Well this works fine for me.
Probably changed something since you created this issue that accidentally fixed this.
Thanks for the report either way! :)
[https://i.imgur.com/vT8eami.jpg](https://i.imgur.com/vT8eami.jpg)
