### ISSUE TITLE
Quest_Hellfire_Peninsula.cpp

### ISSUE THREAD

**Issue by Magnifikator** [arcemu/arcemu#313]
The script Quest_Hellfire_Peninsula.cpp prevents the NPC 20678 to give his only quest 10403.

http://www.wowhead.com/npc=20678#starts

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#20

**Comment by dfighter1985** [comment]
Thanks for the report and the code snippets!
