### ISSUE TITLE
Client crash by dismounting

### ISSUE THREAD

**Issue by Magnifikator** [arcemu/arcemu#351]
If you try to DISmount from one of these 2 mounts than the player wow client crashes.

http://www.wowhead.com/item=37012
http://www.wowhead.com/item=50818

Edit:
- If you don't dismount and instead directly mount to another mount there is no crash. However you will still see the icon of the old mount in the upper right corner.
- Additionally the mounts should change their speed depending on players ability. But they don't. 
- If I drag and drop the icon of these mounts into my action bar the icons disappears after relog.

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#17

**Comment by dfighter1985** [comment]
I'm a bit late to the party, but I think I have an idea

![](https://i.imgur.com/Xet8y6L.jpg)

**Comment by dfighter1985** [comment]
The problems raised in this issue have been mitigated. Thank you for your report.
