### ISSUE TITLE
Visual Studio 2012 Compile fix included

### ISSUE THREAD

**Issue by dRaiNe** [arcemu/arcemu#358]
Can't compile on MSVC 2012 due to /zm bug. How to fix: replace a few lines (starting at 99 line) in your CMake/CMakeLists.txt with this:

```
#This fixes PCH issues 'Inconsistent values for /Ym'
IF( CMAKE_GENERATOR MATCHES Visual* ) 
```
# STRING( REGEX REPLACE "(/Zm)([0-9]+)" "\1${VISUALSTUDIO_COMPILERHEAPLIMIT}" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} )
# STRING( REGEX REPLACE "(/Zm)([0-9]+)" "\1${VISUALSTUDIO_COMPILERHEAPLIMIT}" CMAKE_C_FLAGS ${CMAKE_C_FLAGS} )
# SET( CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} CACHE STRING "CMAKE_CXX_FLAGS" FORCE)
# SET( CMAKE_C_FLAGS ${CMAKE_C_FLAGS} CACHE STRING "CMAKE_C_FLAGS" FORCE)
# Specify the maximum PreCompiled Header memory allocation limit
# Fixes a compiler-problem when using PCH - the /Ym flag is adjusted by the compiler in MSVC2012, hence we need to set an upper limit with /Zm to avoid discrepancies)
# (And yes, this is a verified , unresolved bug with MSVC... _sigh_)

string(REGEX REPLACE "/Zm[0-9]+ _" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm500" CACHE STRING "" FORCE)
    ENDIF( CMAKE_GENERATOR MATCHES Visual_ )
ENDIF()

Then do CMake File>Delete Cache followed by "config" and "generate" buttons.
http://pastebin.com/KLgqDQ45

**Comment by dfighter1985** [comment]
Happy seventh birthday ticket #358 ! Well almost, just a few days away.
I forgot to bring a cake.
Nevertheless I think I will close this as VS2017 builds (see the AppVeyor build) which is newer that VS2012. Either way thank you for sharing this.
