### ISSUE TITLE
CMake 2.8.11

### ISSUE THREAD

**Issue by Magnifikator** [arcemu/arcemu#359]
Please read this:
http://arcemu.org/forums/index.php?showtopic=26746

It tried now half an hour with this fucking Github System to make a pull request. But doesn't work.

Here's the source code:
https://github.com/Magnifikator/arcemu/blob/patch-3/cmake/CMakeLists.txt

Diffs:
https://github.com/Magnifikator/arcemu/commit/dae3ccc5026e082248083cabe6081bc04a0fd98d

**Comment by dfighter1985** [comment]
Sorry for the slight delay.
I use 2.8.12.2 on my dev VM and it works without a problem on both 32 and 64 bit builds.
So I guess this is fixed.
