### ISSUE TITLE
Quest ID 8483 (The Dwarven Spy)

### ISSUE THREAD

**Issue by Keldo** [arcemu/arcemu#390]
Upon starting this quest, the NPC Prospecter Anvilward will state "Follow Me" then just stand there for a moment, he will then take off running and begin bouncing around the building in which this quest takes place, never affording you the ability to complete the quest at hand.

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#12

**Comment by dfighter1985** [comment]
Thanks for the report!
