### ISSUE TITLE
CONNECT TO WOLTK SERVER VIA TBC CLIENT

### ISSUE THREAD

**Issue by mobilemail** [arcemu/arcemu#412]
hello,
i wana connect to woltk server via tbc client,
now i wana know whats is diffrent in tbc server and woltk server 
in socket packets and more...
just in connect to server,
more packets will be changed in later.
thank you

**Comment by Thetruecrow** [comment]
Yes

**Comment by mobilemail** [comment]
How?

**Comment by dfighter1985** [comment]
There are lots of differences.
You will have to check out the latest 2.4.3 version, and compare it to the first WOTLK revision.
Check this revision for the changes:
99ba90f5fed8797b4f6b90a477efe18b2399efa0

**Comment by mobilemail** [comment]
thank you
sorry for bad english,
I mean
I would like to be connected to the server 3.3.5, with all the changes, but the client 2.4.3
I do not mean that I want the Lich King kill or 2.4.3 client to be entered in the map that is related to 3.3.5,
I want the latest version of arcemu with the lowest possible bug I set up a server 2.4.3.
A lot of changes from 2.4.3 to the latest version 3.3.5 has been applied.
I just want to give the client what changes in the last version 2.4.3 to 3.3.5 come into play,
For example, 8606 was equal to my min build version, and the error log onto the server with the client from the server did not receive a lower version,
What other similar changes should I do?

**Comment by jfrantz2** [comment]
Why not just use the intended client? It's also worth mentioning that ArcEmu isn't really maintained any more.

**Comment by mobilemail** [comment]
after that i connect to woltk server via tbc client,i'll make multi client private server.
i mean you can connect to one server with one realm but from you're client build,
first server detect you're build and send packet match you're client;)
i love arcemu!;)

**Comment by jfrantz2** [comment]
Well I know of a few regularly updated forks, try https://github.com/EasyWoW/easywow

**Comment by mobilemail** [comment]
no idea?

**Comment by armm77** [comment]
You can use this emu, https://github.com/AscEmu/AscEmu_TBC or https://github.com/AscEmu/AscEmu

**Comment by dfighter1985** [comment]
You guys shouldn't advertise your projects here.

**Comment by dfighter1985** [comment]
Also it's a very bad idea to allow multiple client versions.
Not only would it be a lot of work, it would also be pointless, since the players couldn't actually play. Game rules changed a lot from version to version.

**Comment by mobilemail** [comment]
i can do this,
this is not issue its a request,
if you can help me tell me,
witch code would be change just for login player to server client2.4.3 server 3.3.5a
if you are busy or dont wana help me close this issue;)
<i'll do this but its hard for me;)>

**Comment by dfighter1985** [comment]
@mobilemail I've already linked the relevant changeset. If you are willing and able to pull this off, you can work from that.

**Comment by mobilemail** [comment]
Hello again,

when i use 2.4.3 client in this code server returned on this lines
WorldSocket.cpp
`	if(memcmp(sha.GetDigest(), digest, 20))
	{
		// AUTH_UNKNOWN_ACCOUNT = 21
		OutPacket(SMSG_AUTH_RESPONSE, 1, "\x15");
		return;
	}`
digest = 0x21daf72c "xœuÏ;Â0€ár.CP¥f¡ÌÌÌÌÌÌÌÌ‹,?™"KZE3¬ëmuÖ~’ÓG°¨";
