### ISSUE TITLE
Battlegrounds.dll build failed unresolved externals

### ISSUE THREAD

**Issue by gcpigni** [arcemu/arcemu#419]
Visual Studio 2010 Express
Windows 10 x64
Release x32

edit: also tried x64 / switched to VS2010 Pro

26>EyeOfTheStorm.obj : error LNK2019: unresolved external symbol "public: static void __cdecl Messenger::SendWorldStateUpdate(class Player *,unsigned int,unsigned int)" (?SendWorldStateUpdate@Messenger@@SAXPAVPlayer@@II@Z) referenced in function "public: void __thiscall EyeOfTheStorm::UpdateCPs(void)" (?UpdateCPs@EyeOfTheStorm@@QAEXXZ)
20>  DruidSpells.cpp
26>C:\ArcEmu\build\battlegrounds\Release\Battlegrounds.dll : fatal error LNK1120: 1 unresolved externals

**Comment by dfighter1985** [comment]
All of the issues you've opened are probably caused by me not maintaining the Windows build. I'll try to take a look this week sometime.

**Comment by gcpigni** [comment]
Thank you dfighter1985. The other files seems to be compiling fine

**Comment by dfighter1985** [comment]
@gcpigni as of the latest commit it builds again on Windows now.

**Comment by gcpigni** [comment]
I know this is a abandoned project so many thanks for your help @dfighter1985 i will not bother again.

pd: Build: 30 succeeded :D

**Comment by dfighter1985** [comment]
Just *mostly* abandoned, as I am the only one who works on it, and even I don't have much free time to do so. Anyhow feel free to open a ticket if I break something, I'll definitely fix it as soon as I can. ;)
