### ISSUE TITLE
Error on load world ?SetDurabilityToMax

### ISSUE THREAD

**Issue by gcpigni** [arcemu/arcemu#421]
Used this commit: 964e9b8
x32 build / VS2017 / W10x32
buildlog: [buildlog.txt](https://github.com/arcemu/arcemu/files/4775636/buildlog.txt)

Hello, something gets wrong with the last changes :D 

Get this message on world start: world.exe Cant find entry procedeture ?SetDurabilityToMax@item@@QAEXXZ
in dinamic lib LuaEngine.dll

 

Also the console display this:

LuaEngine.dll cannot open library
MiscScripts.dll version missmatch
QuestScripts.dll version missmatch
ServerStatusPlugin.dll version missmatch

**Comment by dfighter1985** [comment]
Always re-run CMake and then do a full rebuild when updating.
Try to do so now please, as the problem could be that some files are outdated but cached.

**Comment by gcpigni** [comment]
I always re-run CMake, but i compile with control+shift+b
trying the rebuild option now..

**Comment by dfighter1985** [comment]
This is what I see on a VM with Windows 10, and Visual Studio 2017 build, when it starts up:

![](https://i.imgur.com/wCmp9nF.jpg)

**Comment by gcpigni** [comment]
I believe you :) 
Still having the same problems... Maybe mi local clone of arcemu repo gone mad... i will do a fresh clone

**Comment by gcpigni** [comment]
The fresh clone fixed the problem. Im sorry for waste your time with this bad report

**Comment by dfighter1985** [comment]
Don't worry about it, this can happen to anyone.
I'm glad it works after all :)
