### ISSUE TITLE
4.3.4 a Opcodes Taken from TrinityCore

### ISSUE THREAD

**Issue by Abd-ulRahman** [arcemu/arcemu#422]
Hello,
Good Day,

It's Good to have you back.
Just in case Upgrading to 4.3.4a you'll find in download link TrinityCore 4.3.4 a Opcodes rewrite in Arcemu way.

https://www.mediafire.com/file/ubsksvhxa3vh2rl/4.3.4_Opcodes.rar/file
Hope you'll find it useful.

**Comment by dfighter1985** [comment]
Thanks, but no thanks.
