### ISSUE TITLE
Lua CreateCustomWaypointMap

### ISSUE THREAD

**Issue by gcpigni** [arcemu/arcemu#424]
arcemu commit: #4d2205b
build 32x/W10x64
Maps: yes
Vmaps: unable to make this work for now

Hello, i discover two lua functions broken, however i could be wrong since there arent any examples about this in the forum. 
Edit: the weird thing is i dont have error in console.
```
function LetsMoveOnSpawn( unit, event )
	unit:CreateCustomWaypointMap();
	unit:CreateWaypoint( -8925.13, 538.71, 94.30, 2.14, 5000, 0, 0 );
        unit:CreateWaypoint( -8935.10, 549.11, 94.34, 2.22, 5000, 0, 0 );
end

RegisterUnitEvent( 3509, 18, "LetsMoveOnSpawn" );
```

**Comment by gcpigni** [comment]
Another epic fail of my side. Just in case, here is the snippet of how to make this work:

`function RemyOnSpawn( unit, event )
    unit:CreateCustomWaypointMap()
    unit:CreateCustomWaypoint( 1, -9483.34, 65.21, 56.17, 3.09, 5000, 256, 0 );
    unit:CreateCustomWaypoint( 2, -9487.99, 51.55, 56.39, 3.08, 5000, 256, 0 );
end

RegisterUnitEvent( 241, 18, "RemyOnSpawn" );`

**Comment by dfighter1985** [comment]
Maybe things like this could be documented on Arcemu's Github wiki

**Comment by gcpigni** [comment]
Oh i didnt notice we have a wiki. I could do a little research on how to use it and then start documenting things if you like

**Comment by gcpigni** [comment]
@dfighter1985 tried to add things in the wiki but seens i need some kind of permission

**Comment by dfighter1985** [comment]
> 
> 
> @dfighter1985 tried to add things in the wiki but seens i need some kind of permission

Yes it seems so.  Unfortunately it's a binary choice: either I allow everyone to edit it, or only those with push access to the repo.
So will have to find another solution to this.
Arcemu does have a normal wiki, but it's database has crashed and I couldn't get Hasbro yet to give me access or fix it.

**Comment by dfighter1985** [comment]
How about something like this?
https://arcemu.fandom.com/

If you make an account you can create / edit pages there.

**Comment by gcpigni** [comment]
Not to much fun but it will work :)
