### ISSUE TITLE
Gameobject scale/size problem

### ISSUE THREAD

**Issue by cressidagp** [arcemu/arcemu#426]
arcemu commit: #4d2205b
build 32x/W10x64

Hello, here another bug report.

if you spawn an gameobject from inside the client the go will have a bigger scale. 
How to reproduce this:  lets spawn a chicken egg (161513) or just finish quest (3861) you will get a godzilla size egg. 
Just in case a checked egg size in the database (size=0,2).

**Comment by dfighter1985** [comment]
Latest commit fixed this:
https://i.imgur.com/7oy41sI.jpg
