### ISSUE TITLE
Lua: PerformIngameSpawn() not working in instances

### ISSUE THREAD

**Issue by cressidagp** [arcemu/arcemu#427]
Hello, here another bug report for the future >D

PerformIngameSpawn() works fine for creatures on open world... but didnt work in instances. This could be usefull since currently there are bosses with 4 database entrys (one for each level difficulty) so if this command works we can spawn a boss after checking difficulty.

```
`function instancespawn(event, plr, message, type, language )
if(message == "#spawn")
then
		local id = plr:GetInstanceID();
		local test = PerformIngameSpawn( 1, 476, 631, plr:GetX(), plr:GetY(), plr:GetZ(), 4.42, plr:GetFaction(), 0, 0, 0, 0, 0 );
                local test2 = PerformIngameSpawn( 1, 476, 631, plr:GetX(), plr:GetY(), plr:GetZ(), 4.42, plr:GetFaction(), 0, 0, 0, 0, id, 0 );

end
end

RegisterServerHook( 16, "instancespawn" );`
```

**Comment by dfighter1985** [comment]
This is a very bad idea because of multi-threading issues.
You can use Unit:SpawnCreature instead.
