### ISSUE TITLE
Warrior Quest: The Affray

### ISSUE THREAD

**Issue by ghost** [arcemu/arcemu#45]
Quest is not solvable as BigWill is not spawned upon entering the battle area on fray island.
Which leads me to a bigger question/issue:
In your rep. there are lua and c++ scripts parallel, some instances are partially scripted lua, some c++.
The wiki doesn't explain things fully, are those Lua scripts all implemented by default or do you have to drop them in the script
folder manually? I am asking this because a quest like this could be easily scripted with lua (and from what I see the lua engine of Arc has a high potential, it is even possible to script many instance events in it)
I could even do some simple things if I have some spare time but I don't want to mess with lua scripts if you prefer to code it all in c++ src. I'm just not certain about the pros/and cons there obviously has to be a reason why some scripts are lua, some c++.
So I would be very thankful for some sort of explanation ;)

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#87

**Comment by dfighter1985** [comment]
I'm going to close this and track progress in the newer issue #409 as that has more details.
