### ISSUE TITLE
#219: Vehicle Faction Bug?

### ISSUE THREAD

**Issue by ghost** [arcemu/arcemu#7]
I use Arc Rev from 2011-11-07 14:53:52 (Sorry couldn't figure which
 Changeset in GIT) with latest WhyDB Rev 157

 I don't know what it is like on retail but when you enter a vehicle it
 should probably take on your faction ID. For instance the horse vehicles
 in The Scarlet Enclave keep their faction, so when you take a ride into
 Death Breach, all the NPC's that are friendly to you will kill your horse
 and then leave you alone.

 Maybe this is not a core issue and on retail servers the horse vehicles
 just have a different faction by default, in this case i apologize for
 bothering you with this bug.

 As the entire DK starting area needs scripting I just posted this because
 it might be an issue to vehicles in general.

 Keep up the good work ;)

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#97

**Comment by dfighter1985** [comment]
Fixed in latest version.
